import { PostType } from "../types/community";

export const samplePosts: PostType[] = [
  {
    id: 1,
    title: "포스트 제목",
    body: "포스트 내용",
    forum_id: 1,
    forum_name: "야구톡",
    userId: 1,
    author_name: "작성자",
    created_at: "6분전",
    updated_at: "6분전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 1,
  },
  {
    id: 2,
    title: "포스트2 제목",
    body: "포스트2 내용",
    forum_id: 1,
    forum_name: "야구톡",
    userId: 1,
    author_name: "작성자",
    created_at: "13분전",
    updated_at: "8분전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 1,
  },
  {
    id: 3,
    title: "5월 15일 13시 목동야구장 용병",
    body: "5월 15일 경기 용병 구합니다.",
    forum_id: 2,
    forum_name: "모집",
    userId: 1,
    author_name: "작성자",
    created_at: "1시간전",
    updated_at: "1시간전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 165,
  },
  {
    id: 4,
    title: "5월 5일 성남 1부 경기",
    body: "5월 5일 성남 1부 경기 용병 구합니다.",
    forum_id: 2,
    forum_name: "모집",
    userId: 1,
    author_name: "작성자",
    created_at: "13시간전",
    updated_at: "13시간전",
    num_comments: 2,
    num_likes: 0,
    num_clicks: 54,
  },
  {
    id: 5,
    title: "백호 존나 못하네 ㅋㅋ",
    body: "홍승우가 백호보단 잘할듯",
    forum_id: 1,
    forum_name: "야구톡",
    userId: 1,
    author_name: "작성자",
    created_at: "1시간전",
    updated_at: "1시간전",
    num_comments: 12,
    num_likes: 134,
    num_clicks: 1287,
  },
  {
    id: 6,
    title: "제목제목제목제목제목",
    body: "내용내용내용내용내용",
    forum_id: 1,
    forum_name: "야구톡",
    userId: 1,
    author_name: "작성자",
    created_at: "1시간전",
    updated_at: "1시간전",
    num_comments: 12,
    num_likes: 134,
    num_clicks: 1287,
  },
];
