import { PostType } from "../types/community";

export const samplePosts: PostType[] = [
  {
    id: 1,
    title: "포스트 제목",
    body: "포스트 내용",
    userId: 1,
    author_name: "작성자",
    created_at: "6분전",
    updated_at: "6분전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 1,
  },
  {
    id: 2,
    title: "포스트2 제목",
    body: "포스트2 내용",
    userId: 1,
    author_name: "작성자",
    created_at: "13분전",
    updated_at: "8분전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 1,
  },
  {
    id: 3,
    title: "5월 15일 13시 목동야구장 용병",
    body: "5월 15일 경기 용병 구합니다.",
    userId: 1,
    author_name: "작성자",
    created_at: "1시간전",
    updated_at: "1시간전",
    num_comments: 1,
    num_likes: 1,
    num_clicks: 165,
  },
  {
    id: 4,
    title: "5월 5일 성남 1부 경기",
    body: "5월 5일 성남 1부 경기 용병 구합니다.",
    userId: 1,
    author_name: "작성자",
    created_at: "13시간전",
    updated_at: "13시간전",
    num_comments: 2,
    num_likes: 0,
    num_clicks: 54,
  },
];
