export const themeColors = {
  primary: "green",
  //onPrimary: "white",
  primaryContainer: "#fff",
  //onPrimaryContainer: "white",
  secondary: "brown",
  //onSecondary: "white",
  secondaryContainer: "rgba(192, 192, 192, 0.35)",
  onSecondaryContainer: "white", // 탭 아이콘 색상, 칩 오른쪽 아이콘 색상
  tertiary: "gray",
  //onTertiary: "white",
  tertiaryContainer: "rgba(64, 196, 20, 0.5)",
  //onTertiaryContainer: "white",
  error: "red",
  //onError: "white",
  //errorContainer: "white",
  //onErrorContainer: "white",
  background: "rgba(64, 196, 20, 0.25)",
  onBackground: "black",
  surface: "rgba(64, 196, 20, 0.5)",
  onSurface: "black",
  surfaceVariant: "rgba(64, 196, 20, 0.25)",
  onSurfaceVariant: "black",
  outline: "gray",
};
