name: Coverage

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./CatchB/yarn.lock"

      - name: Build
        run: |
          cd CatchB
          yarn
          CI=true yarn test --coverage --watchAll=false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./CatchB/coverage/lcov.info
